################
# See:
# https://docs.travis-ci.com/user/getting-started/
################

################
# Use container-based infrastructure on Travis:
#sudo: false
################

################
# https://docs.travis-ci.com/user/multi-os/
#os:
#  - osx # needs more work, maybe download miniconda first
#  - linux
################

################
# Copied from: https://docs.travis-ci.com/user/languages/python/
language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.5           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
          - choco install python
          - pip install -U pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
#script: python3 my_app.py || python my_app.py
################

################
# Specify runtime and versions
# See: https://docs.travis-ci.com/user/customizing-the-build/#Specifying-Runtime-Versions
#dist: xenial
#language: python
#python:
#  - "3.5"
#  - "3.6"
#  - "3.7"
################

################
# Install dependencies:
install:
  - pip install -r requirements.txt # --use-mirrors errors in Py3.5
  - python setup.py install
  - pip install flake8
#  - pip install coverage # coveralls.io continuously monitors test case coverage
#  - pip install coveralls
################

################
# Indicate what to do before script, what script to execute and what to do after this:
# flake8 is wrapper for pep8, pyflakes and McCabe. 
# pep8 checks the PEP 0008 style
# pyflakes looks for e.g. unused imports or variables
# McCabe warns about (unnecessary) complicated code

before_script:
    - flake8 .

# command to run tests
script: 
  - pytest -rP -v --cache-clear
#  - coverage run --source=project_quickstart setup.py test

#after_success:
#    coveralls
################
